version: "3.8"
services:
  app1:
    container_name: app1
    build:
      context: .
      target: php
      args:
        - APP_ENV=${APP_ENV}
    environment:
      - APP_ENV=${APP_ENV}
    working_dir: /var/www
    volumes:
      - ./:/var/www
    ports:
      - "8081:8080"
      - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
    depends_on:
      database1:
        condition: service_healthy
    networks:
        - inertia
  database1:
    container_name: database1
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    volumes:
      - db-data:/var/lib/mysql
    healthcheck:
        test: [ "CMD", "mysqladmin" ,"ping", "-p", "-p${DB_PASSWORD}" ]
        retries: 3
        timeout: 10s
    networks:
        - inertia
volumes:
  db-data: ~
networks:
    inertia:
        driver: bridge
