version: "3.8"
services:
  app1:
    container_name: app1
    build:
      context: .
      target: php
      args:
        - APP_ENV=${APP_ENV}
    environment:
      - APP_ENV=${APP_ENV}
    working_dir: /var/www
    volumes:
      - ./:/var/www
    ports:
      - "8081:8080"
      - '5174:5174'
    networks:
        - mysql-container_mysql_network
networks:
    mysql-container_mysql_network:
        external: true
